// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Model struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Version       string             `json:"version"`
	Description   string             `json:"description"`
	Mode          string             `json:"mode"`
	ConfigSchema  []byte             `json:"config_schema"`
	RuntimeCompat string             `json:"runtime_compat"`
	Author        string             `json:"author"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Simulation struct {
	ID           string             `json:"id"`
	ModelID      string             `json:"model_id"`
	ModelVersion string             `json:"model_version"`
	Seed         int64              `json:"seed"`
	Mode         string             `json:"mode"`
	Status       string             `json:"status"`
	Config       []byte             `json:"config"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	OwnerID      pgtype.Text        `json:"owner_id"`
}

type Snapshot struct {
	ID            string             `json:"id"`
	SimulationID  string             `json:"simulation_id"`
	SchemaVersion int32              `json:"schema_version"`
	EngineVersion string             `json:"engine_version"`
	Data          []byte             `json:"data"`
	Checksum      string             `json:"checksum"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           string             `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
