// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlc

import (
	"context"
)

const createSimulation = `-- name: CreateSimulation :one
INSERT INTO simulations (id, model_id, model_version, seed, mode, status, config)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, model_id, model_version, seed, mode, status, config, created_at, updated_at, completed_at
`

type CreateSimulationParams struct {
	ID           string `json:"id"`
	ModelID      string `json:"model_id"`
	ModelVersion string `json:"model_version"`
	Seed         int64  `json:"seed"`
	Mode         string `json:"mode"`
	Status       string `json:"status"`
	Config       []byte `json:"config"`
}

func (q *Queries) CreateSimulation(ctx context.Context, arg CreateSimulationParams) (Simulation, error) {
	row := q.db.QueryRow(ctx, createSimulation,
		arg.ID,
		arg.ModelID,
		arg.ModelVersion,
		arg.Seed,
		arg.Mode,
		arg.Status,
		arg.Config,
	)
	var i Simulation
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.ModelVersion,
		&i.Seed,
		&i.Mode,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getModel = `-- name: GetModel :one
SELECT id, name, version, description, mode, config_schema, runtime_compat, author, created_at
FROM models
WHERE id = $1 AND version = $2
`

type GetModelParams struct {
	ID      string `json:"id"`
	Version string `json:"version"`
}

func (q *Queries) GetModel(ctx context.Context, arg GetModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, getModel, arg.ID, arg.Version)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Mode,
		&i.ConfigSchema,
		&i.RuntimeCompat,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const getSimulation = `-- name: GetSimulation :one
SELECT id, model_id, model_version, seed, mode, status, config, created_at, updated_at, completed_at
FROM simulations
WHERE id = $1
`

func (q *Queries) GetSimulation(ctx context.Context, id string) (Simulation, error) {
	row := q.db.QueryRow(ctx, getSimulation, id)
	var i Simulation
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.ModelVersion,
		&i.Seed,
		&i.Mode,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, simulation_id, schema_version, engine_version, data, checksum, created_at
FROM snapshots
WHERE id = $1
`

func (q *Queries) GetSnapshot(ctx context.Context, id string) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshot, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.SimulationID,
		&i.SchemaVersion,
		&i.EngineVersion,
		&i.Data,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const listModelVersions = `-- name: ListModelVersions :many
SELECT id, name, version, description, mode, config_schema, runtime_compat, author, created_at
FROM models
WHERE id = $1
ORDER BY version
`

func (q *Queries) ListModelVersions(ctx context.Context, id string) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModelVersions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Mode,
			&i.ConfigSchema,
			&i.RuntimeCompat,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, name, version, description, mode, config_schema, runtime_compat, author, created_at
FROM models
ORDER BY id, version
`

func (q *Queries) ListModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Mode,
			&i.ConfigSchema,
			&i.RuntimeCompat,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimulations = `-- name: ListSimulations :many
SELECT id, model_id, model_version, seed, mode, status, config, created_at, updated_at, completed_at
FROM simulations
ORDER BY created_at DESC
`

func (q *Queries) ListSimulations(ctx context.Context) ([]Simulation, error) {
	rows, err := q.db.Query(ctx, listSimulations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Simulation
	for rows.Next() {
		var i Simulation
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.ModelVersion,
			&i.Seed,
			&i.Mode,
			&i.Status,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, simulation_id, schema_version, engine_version, data, checksum, created_at
FROM snapshots
WHERE simulation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSnapshots(ctx context.Context, simulationID string) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshots, simulationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.SimulationID,
			&i.SchemaVersion,
			&i.EngineVersion,
			&i.Data,
			&i.Checksum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSnapshot = `-- name: SaveSnapshot :exec
INSERT INTO snapshots (id, simulation_id, schema_version, engine_version, data, checksum)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveSnapshotParams struct {
	ID            string `json:"id"`
	SimulationID  string `json:"simulation_id"`
	SchemaVersion int32  `json:"schema_version"`
	EngineVersion string `json:"engine_version"`
	Data          []byte `json:"data"`
	Checksum      string `json:"checksum"`
}

func (q *Queries) SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error {
	_, err := q.db.Exec(ctx, saveSnapshot,
		arg.ID,
		arg.SimulationID,
		arg.SchemaVersion,
		arg.EngineVersion,
		arg.Data,
		arg.Checksum,
	)
	return err
}

const updateSimulationStatus = `-- name: UpdateSimulationStatus :one
UPDATE simulations
SET status = $2,
    updated_at = now(),
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'stopped') THEN now() ELSE completed_at END
WHERE id = $1
RETURNING id, model_id, model_version, seed, mode, status, config, created_at, updated_at, completed_at
`

type UpdateSimulationStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSimulationStatus(ctx context.Context, arg UpdateSimulationStatusParams) (Simulation, error) {
	row := q.db.QueryRow(ctx, updateSimulationStatus, arg.ID, arg.Status)
	var i Simulation
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.ModelVersion,
		&i.Seed,
		&i.Mode,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const upsertModel = `-- name: UpsertModel :exec
INSERT INTO models (id, name, version, description, mode, config_schema, runtime_compat, author)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id, version) DO UPDATE SET
    name          = EXCLUDED.name,
    description   = EXCLUDED.description,
    mode          = EXCLUDED.mode,
    config_schema = EXCLUDED.config_schema,
    runtime_compat = EXCLUDED.runtime_compat,
    author        = EXCLUDED.author
`

type UpsertModelParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Version       string `json:"version"`
	Description   string `json:"description"`
	Mode          string `json:"mode"`
	ConfigSchema  []byte `json:"config_schema"`
	RuntimeCompat string `json:"runtime_compat"`
	Author        string `json:"author"`
}

func (q *Queries) UpsertModel(ctx context.Context, arg UpsertModelParams) error {
	_, err := q.db.Exec(ctx, upsertModel,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Mode,
		arg.ConfigSchema,
		arg.RuntimeCompat,
		arg.Author,
	)
	return err
}
