// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateSimulation(ctx context.Context, arg CreateSimulationParams) (Simulation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSimulation(ctx context.Context, id string) error
	GetModel(ctx context.Context, arg GetModelParams) (Model, error)
	GetSimulation(ctx context.Context, id string) (Simulation, error)
	GetSnapshot(ctx context.Context, id string) (Snapshot, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListModelVersions(ctx context.Context, id string) ([]Model, error)
	ListModels(ctx context.Context) ([]Model, error)
	ListSimulations(ctx context.Context) ([]Simulation, error)
	ListSnapshots(ctx context.Context, simulationID string) ([]Snapshot, error)
	SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error
	UpdateSimulationStatus(ctx context.Context, arg UpdateSimulationStatusParams) (Simulation, error)
	UpsertModel(ctx context.Context, arg UpsertModelParams) error
}

var _ Querier = (*Queries)(nil)
