apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simulator.fullname" . }}-secret
  labels:
    {{- include "simulator.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret | quote }}
